language: julia
os:
  - linux
  - osx
julia:
  - 1.1

after_success:  # only run this if test pass
  - julia -e 'using Pkg; Pkg.add("Coverage");
      using Coverage; Codecov.submit(Codecov.process_folder())';